services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_HOSTNAME: localhost
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    command:
      - start-dev

  postgres:
    image: postgres:latest
    environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
      - "40000:40000"
    environment:
        KEYCLOAK_URL: http://keycloak:8080
        KEYCLOAK_REALM: master
        KEYCLOAK_CLIENT_ID: admin-cli
        KEYCLOAK_CLIENT_SECRET: 7b3b3b3e-7b3b-4b3b-8b3b-7b3b3b3b3b3b
    depends_on:
      - keycloak

volumes:
    postgres-data:
